#!/usr/bin/env ruby

require 'bundler'
require 'benchmark'

$stdout.print 'Loading Bundler: '
bm = Benchmark.measure { |_| Bundler.setup }
$stdout.print "loaded in #{bm.total.round(3)}s\n"

require_relative './lib/elastic_ruby'

ElasticRuby::Cli.start
